[build]
  command = "npm run build"
  functions = "netlify/functions"
  publish = "dist/public"

[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/api/:splat"
  status = 200

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[build.environment]
  NODE_VERSION = "18"
  NPM_FLAGS = "--production=false"

[functions]
  external_node_modules = ["@neondatabase/serverless", "drizzle-orm", "@google/genai", "ws", "zod"]